-- Examples and availability, carried over from the frontend's static
-- sorting guide so that removing that file loses nothing.
--
-- Generated from frontend/src/data/sortingGuide.ts rather than typed by
-- hand: 192 statements across 12 items and three languages is exactly the
-- kind of transcription where a silent mistake hides.

insert into sorting_item_example (item_id, language_code, position, example) values (1, 'fr', 0, 'fruits');
insert into sorting_item_example (item_id, language_code, position, example) values (1, 'fr', 1, 'legumes');
insert into sorting_item_example (item_id, language_code, position, example) values (1, 'fr', 2, 'pain');
insert into sorting_item_example (item_id, language_code, position, example) values (1, 'fr', 3, 'pates');
insert into sorting_item_example (item_id, language_code, position, example) values (1, 'fr', 4, 'viande');
insert into sorting_item_example (item_id, language_code, position, example) values (1, 'fr', 5, 'poisson');
insert into sorting_item_example (item_id, language_code, position, example) values (1, 'fr', 6, 'coquilles d''oeufs');
insert into sorting_item_example (item_id, language_code, position, example) values (1, 'fr', 7, 'cafe');
insert into sorting_item_example (item_id, language_code, position, example) values (1, 'fr', 8, 'the');
insert into sorting_item_example (item_id, language_code, position, example) values (1, 'en', 0, 'fruit');
insert into sorting_item_example (item_id, language_code, position, example) values (1, 'en', 1, 'vegetables');
insert into sorting_item_example (item_id, language_code, position, example) values (1, 'en', 2, 'bread');
insert into sorting_item_example (item_id, language_code, position, example) values (1, 'en', 3, 'pasta');
insert into sorting_item_example (item_id, language_code, position, example) values (1, 'en', 4, 'meat');
insert into sorting_item_example (item_id, language_code, position, example) values (1, 'en', 5, 'fish');
insert into sorting_item_example (item_id, language_code, position, example) values (1, 'en', 6, 'egg shells');
insert into sorting_item_example (item_id, language_code, position, example) values (1, 'en', 7, 'coffee');
insert into sorting_item_example (item_id, language_code, position, example) values (1, 'en', 8, 'tea');
insert into sorting_item_example (item_id, language_code, position, example) values (1, 'zh', 0, '水果');
insert into sorting_item_example (item_id, language_code, position, example) values (1, 'zh', 1, '蔬菜');
insert into sorting_item_example (item_id, language_code, position, example) values (1, 'zh', 2, '面包');
insert into sorting_item_example (item_id, language_code, position, example) values (1, 'zh', 3, '意面');
insert into sorting_item_example (item_id, language_code, position, example) values (1, 'zh', 4, '肉');
insert into sorting_item_example (item_id, language_code, position, example) values (1, 'zh', 5, '鱼');
insert into sorting_item_example (item_id, language_code, position, example) values (1, 'zh', 6, '蛋壳');
insert into sorting_item_example (item_id, language_code, position, example) values (1, 'zh', 7, '咖啡渣');
insert into sorting_item_example (item_id, language_code, position, example) values (1, 'zh', 8, '茶叶');
insert into sorting_item_example (item_id, language_code, position, example) values (5, 'fr', 0, 'feuilles');
insert into sorting_item_example (item_id, language_code, position, example) values (5, 'fr', 1, 'fleurs');
insert into sorting_item_example (item_id, language_code, position, example) values (5, 'fr', 2, 'gazon');
insert into sorting_item_example (item_id, language_code, position, example) values (5, 'fr', 3, 'mauvaises herbes');
insert into sorting_item_example (item_id, language_code, position, example) values (5, 'fr', 4, 'petites branches');
insert into sorting_item_example (item_id, language_code, position, example) values (5, 'en', 0, 'leaves');
insert into sorting_item_example (item_id, language_code, position, example) values (5, 'en', 1, 'flowers');
insert into sorting_item_example (item_id, language_code, position, example) values (5, 'en', 2, 'grass');
insert into sorting_item_example (item_id, language_code, position, example) values (5, 'en', 3, 'weeds');
insert into sorting_item_example (item_id, language_code, position, example) values (5, 'en', 4, 'small branches');
insert into sorting_item_example (item_id, language_code, position, example) values (5, 'zh', 0, '树叶');
insert into sorting_item_example (item_id, language_code, position, example) values (5, 'zh', 1, '花');
insert into sorting_item_example (item_id, language_code, position, example) values (5, 'zh', 2, '草屑');
insert into sorting_item_example (item_id, language_code, position, example) values (5, 'zh', 3, '杂草');
insert into sorting_item_example (item_id, language_code, position, example) values (5, 'zh', 4, '小树枝');
insert into sorting_item_example (item_id, language_code, position, example) values (6, 'fr', 0, 'boite a pizza');
insert into sorting_item_example (item_id, language_code, position, example) values (6, 'fr', 1, 'assiette en carton');
insert into sorting_item_example (item_id, language_code, position, example) values (6, 'fr', 2, 'essuie-tout');
insert into sorting_item_example (item_id, language_code, position, example) values (6, 'fr', 3, 'mouchoir');
insert into sorting_item_example (item_id, language_code, position, example) values (6, 'fr', 4, 'sac en papier');
insert into sorting_item_example (item_id, language_code, position, example) values (6, 'en', 0, 'pizza box');
insert into sorting_item_example (item_id, language_code, position, example) values (6, 'en', 1, 'paper plate');
insert into sorting_item_example (item_id, language_code, position, example) values (6, 'en', 2, 'paper towel');
insert into sorting_item_example (item_id, language_code, position, example) values (6, 'en', 3, 'tissue');
insert into sorting_item_example (item_id, language_code, position, example) values (6, 'en', 4, 'paper bag');
insert into sorting_item_example (item_id, language_code, position, example) values (6, 'zh', 0, '披萨盒');
insert into sorting_item_example (item_id, language_code, position, example) values (6, 'zh', 1, '纸盘');
insert into sorting_item_example (item_id, language_code, position, example) values (6, 'zh', 2, '厨房纸');
insert into sorting_item_example (item_id, language_code, position, example) values (6, 'zh', 3, '纸巾');
insert into sorting_item_example (item_id, language_code, position, example) values (6, 'zh', 4, '纸袋');
insert into sorting_item_example (item_id, language_code, position, example) values (7, 'fr', 0, 'pots');
insert into sorting_item_example (item_id, language_code, position, example) values (7, 'fr', 1, 'contenants alimentaires');
insert into sorting_item_example (item_id, language_code, position, example) values (7, 'fr', 2, 'boites en carton');
insert into sorting_item_example (item_id, language_code, position, example) values (7, 'fr', 3, 'papier d''aluminium');
insert into sorting_item_example (item_id, language_code, position, example) values (7, 'fr', 4, 'sacs de plastique');
insert into sorting_item_example (item_id, language_code, position, example) values (7, 'en', 0, 'jars');
insert into sorting_item_example (item_id, language_code, position, example) values (7, 'en', 1, 'food containers');
insert into sorting_item_example (item_id, language_code, position, example) values (7, 'en', 2, 'cardboard boxes');
insert into sorting_item_example (item_id, language_code, position, example) values (7, 'en', 3, 'aluminum foil');
insert into sorting_item_example (item_id, language_code, position, example) values (7, 'en', 4, 'plastic bags');
insert into sorting_item_example (item_id, language_code, position, example) values (7, 'zh', 0, '罐子');
insert into sorting_item_example (item_id, language_code, position, example) values (7, 'zh', 1, '食品容器');
insert into sorting_item_example (item_id, language_code, position, example) values (7, 'zh', 2, '纸箱');
insert into sorting_item_example (item_id, language_code, position, example) values (7, 'zh', 3, '铝箔');
insert into sorting_item_example (item_id, language_code, position, example) values (7, 'zh', 4, '塑料袋');
insert into sorting_item_example (item_id, language_code, position, example) values (8, 'fr', 0, 'journaux');
insert into sorting_item_example (item_id, language_code, position, example) values (8, 'fr', 1, 'circulaires');
insert into sorting_item_example (item_id, language_code, position, example) values (8, 'fr', 2, 'enveloppes');
insert into sorting_item_example (item_id, language_code, position, example) values (8, 'fr', 3, 'feuilles');
insert into sorting_item_example (item_id, language_code, position, example) values (8, 'fr', 4, 'cahiers');
insert into sorting_item_example (item_id, language_code, position, example) values (8, 'en', 0, 'newspapers');
insert into sorting_item_example (item_id, language_code, position, example) values (8, 'en', 1, 'flyers');
insert into sorting_item_example (item_id, language_code, position, example) values (8, 'en', 2, 'envelopes');
insert into sorting_item_example (item_id, language_code, position, example) values (8, 'en', 3, 'paper sheets');
insert into sorting_item_example (item_id, language_code, position, example) values (8, 'en', 4, 'notebooks');
insert into sorting_item_example (item_id, language_code, position, example) values (8, 'zh', 0, '报纸');
insert into sorting_item_example (item_id, language_code, position, example) values (8, 'zh', 1, '传单');
insert into sorting_item_example (item_id, language_code, position, example) values (8, 'zh', 2, '信封');
insert into sorting_item_example (item_id, language_code, position, example) values (8, 'zh', 3, '纸张');
insert into sorting_item_example (item_id, language_code, position, example) values (8, 'zh', 4, '笔记本');
insert into sorting_item_example (item_id, language_code, position, example) values (9, 'fr', 0, 'couches');
insert into sorting_item_example (item_id, language_code, position, example) values (9, 'fr', 1, 'produits hygieniques');
insert into sorting_item_example (item_id, language_code, position, example) values (9, 'fr', 2, 'jouets brises');
insert into sorting_item_example (item_id, language_code, position, example) values (9, 'fr', 3, 'vaisselle cassee');
insert into sorting_item_example (item_id, language_code, position, example) values (9, 'fr', 4, 'ampoules autres que DEL');
insert into sorting_item_example (item_id, language_code, position, example) values (9, 'en', 0, 'diapers');
insert into sorting_item_example (item_id, language_code, position, example) values (9, 'en', 1, 'hygiene products');
insert into sorting_item_example (item_id, language_code, position, example) values (9, 'en', 2, 'broken toys');
insert into sorting_item_example (item_id, language_code, position, example) values (9, 'en', 3, 'broken dishes');
insert into sorting_item_example (item_id, language_code, position, example) values (9, 'en', 4, 'non-LED light bulbs');
insert into sorting_item_example (item_id, language_code, position, example) values (9, 'zh', 0, '尿布');
insert into sorting_item_example (item_id, language_code, position, example) values (9, 'zh', 1, '卫生用品');
insert into sorting_item_example (item_id, language_code, position, example) values (9, 'zh', 2, '损坏的玩具');
insert into sorting_item_example (item_id, language_code, position, example) values (9, 'zh', 3, '破碎餐具');
insert into sorting_item_example (item_id, language_code, position, example) values (9, 'zh', 4, '非 LED 灯泡');
insert into sorting_item_example (item_id, language_code, position, example) values (10, 'fr', 0, 'peinture');
insert into sorting_item_example (item_id, language_code, position, example) values (10, 'fr', 1, 'piles');
insert into sorting_item_example (item_id, language_code, position, example) values (10, 'fr', 2, 'electroniques');
insert into sorting_item_example (item_id, language_code, position, example) values (10, 'fr', 3, 'pneus');
insert into sorting_item_example (item_id, language_code, position, example) values (10, 'fr', 4, 'aerosols');
insert into sorting_item_example (item_id, language_code, position, example) values (10, 'fr', 5, 'huiles');
insert into sorting_item_example (item_id, language_code, position, example) values (10, 'fr', 6, 'polystyrene');
insert into sorting_item_example (item_id, language_code, position, example) values (10, 'en', 0, 'paint');
insert into sorting_item_example (item_id, language_code, position, example) values (10, 'en', 1, 'batteries');
insert into sorting_item_example (item_id, language_code, position, example) values (10, 'en', 2, 'electronics');
insert into sorting_item_example (item_id, language_code, position, example) values (10, 'en', 3, 'tires');
insert into sorting_item_example (item_id, language_code, position, example) values (10, 'en', 4, 'aerosols');
insert into sorting_item_example (item_id, language_code, position, example) values (10, 'en', 5, 'oil');
insert into sorting_item_example (item_id, language_code, position, example) values (10, 'en', 6, 'polystyrene');
insert into sorting_item_example (item_id, language_code, position, example) values (10, 'zh', 0, '油漆');
insert into sorting_item_example (item_id, language_code, position, example) values (10, 'zh', 1, '电池');
insert into sorting_item_example (item_id, language_code, position, example) values (10, 'zh', 2, '电子产品');
insert into sorting_item_example (item_id, language_code, position, example) values (10, 'zh', 3, '轮胎');
insert into sorting_item_example (item_id, language_code, position, example) values (10, 'zh', 4, '喷雾罐');
insert into sorting_item_example (item_id, language_code, position, example) values (10, 'zh', 5, '油类');
insert into sorting_item_example (item_id, language_code, position, example) values (10, 'zh', 6, '泡沫塑料');
update sorting_item_translation set availability = 'Sur demande seulement. Faire la demande au plus tard le dernier jour du mois precedent. Deposer en bordure de rue entre dimanche 18 h et lundi 7 h durant la semaine du deuxieme lundi du mois.' where item_id = 11 and language_code = 'fr';
insert into sorting_item_example (item_id, language_code, position, example) values (11, 'fr', 0, 'matelas');
insert into sorting_item_example (item_id, language_code, position, example) values (11, 'fr', 1, 'fauteuil');
insert into sorting_item_example (item_id, language_code, position, example) values (11, 'fr', 2, 'meuble de jardin');
insert into sorting_item_example (item_id, language_code, position, example) values (11, 'fr', 3, 'laveuse');
insert into sorting_item_example (item_id, language_code, position, example) values (11, 'fr', 4, 'secheuse');
insert into sorting_item_example (item_id, language_code, position, example) values (11, 'fr', 5, 'tapis');
insert into sorting_item_example (item_id, language_code, position, example) values (11, 'fr', 6, 'lavabo');
insert into sorting_item_example (item_id, language_code, position, example) values (11, 'fr', 7, 'toilette');
update sorting_item_translation set availability = 'Request only. Submit the request no later than the last day of the previous month. Place items curbside between Sunday 6:00 PM and Monday 7:00 AM during the week of the second Monday of the month.' where item_id = 11 and language_code = 'en';
insert into sorting_item_example (item_id, language_code, position, example) values (11, 'en', 0, 'mattress');
insert into sorting_item_example (item_id, language_code, position, example) values (11, 'en', 1, 'armchair');
insert into sorting_item_example (item_id, language_code, position, example) values (11, 'en', 2, 'patio furniture');
insert into sorting_item_example (item_id, language_code, position, example) values (11, 'en', 3, 'washer');
insert into sorting_item_example (item_id, language_code, position, example) values (11, 'en', 4, 'dryer');
insert into sorting_item_example (item_id, language_code, position, example) values (11, 'en', 5, 'carpet');
insert into sorting_item_example (item_id, language_code, position, example) values (11, 'en', 6, 'sink');
insert into sorting_item_example (item_id, language_code, position, example) values (11, 'en', 7, 'toilet');
update sorting_item_translation set availability = '仅限提前申请。最晚要在前一个月最后一天前申请。大件垃圾应在当月第二个星期一那一周，周日 18:00 至周一 7:00 之间放到路边。' where item_id = 11 and language_code = 'zh';
insert into sorting_item_example (item_id, language_code, position, example) values (11, 'zh', 0, '床垫');
insert into sorting_item_example (item_id, language_code, position, example) values (11, 'zh', 1, '扶手椅');
insert into sorting_item_example (item_id, language_code, position, example) values (11, 'zh', 2, '庭院家具');
insert into sorting_item_example (item_id, language_code, position, example) values (11, 'zh', 3, '洗衣机');
insert into sorting_item_example (item_id, language_code, position, example) values (11, 'zh', 4, '烘干机');
insert into sorting_item_example (item_id, language_code, position, example) values (11, 'zh', 5, '地毯');
insert into sorting_item_example (item_id, language_code, position, example) values (11, 'zh', 6, '洗手盆');
insert into sorting_item_example (item_id, language_code, position, example) values (11, 'zh', 7, '马桶');
update sorting_item_translation set availability = 'Collecte gratuite sur demande en mai, juin et octobre. Les branches doivent deja etre en bordure de rue avant la demande.' where item_id = 12 and language_code = 'fr';
insert into sorting_item_example (item_id, language_code, position, example) values (12, 'fr', 0, 'branches non attachees');
insert into sorting_item_example (item_id, language_code, position, example) values (12, 'fr', 1, 'petites branches');
insert into sorting_item_example (item_id, language_code, position, example) values (12, 'fr', 2, 'residus de taille');
update sorting_item_translation set availability = 'Free request-based collection in May, June, and October. Branches must already be curbside before the request is submitted.' where item_id = 12 and language_code = 'en';
insert into sorting_item_example (item_id, language_code, position, example) values (12, 'en', 0, 'loose branches');
insert into sorting_item_example (item_id, language_code, position, example) values (12, 'en', 1, 'small branches');
insert into sorting_item_example (item_id, language_code, position, example) values (12, 'en', 2, 'pruning waste');
update sorting_item_translation set availability = '5 月、6 月和 10 月可申请免费收树枝。申请前树枝必须已经放在路边。' where item_id = 12 and language_code = 'zh';
insert into sorting_item_example (item_id, language_code, position, example) values (12, 'zh', 0, '未捆绑树枝');
insert into sorting_item_example (item_id, language_code, position, example) values (12, 'zh', 1, '小树枝');
insert into sorting_item_example (item_id, language_code, position, example) values (12, 'zh', 2, '修剪下来的树枝');
update sorting_item_translation set availability = 'Demande a partir de decembre. La collecte commence la premiere semaine de janvier et dure environ deux semaines sur tout le territoire.' where item_id = 13 and language_code = 'fr';
insert into sorting_item_example (item_id, language_code, position, example) values (13, 'fr', 0, 'sapin naturel');
insert into sorting_item_example (item_id, language_code, position, example) values (13, 'fr', 1, 'arbre de Noel sans decoration');
update sorting_item_translation set availability = 'Requests open in December. Collection starts in the first week of January and lasts about two weeks city-wide.' where item_id = 13 and language_code = 'en';
insert into sorting_item_example (item_id, language_code, position, example) values (13, 'en', 0, 'natural tree');
insert into sorting_item_example (item_id, language_code, position, example) values (13, 'en', 1, 'undecorated Christmas tree');
update sorting_item_translation set availability = '12 月开始申请。收集通常从 1 月第一周开始，全市约持续两周。' where item_id = 13 and language_code = 'zh';
insert into sorting_item_example (item_id, language_code, position, example) values (13, 'zh', 0, '天然圣诞树');
insert into sorting_item_example (item_id, language_code, position, example) values (13, 'zh', 1, '没有装饰的圣诞树');
update sorting_item_translation set availability = 'Service gratuit plusieurs fois par annee. Prochaine date affichee par la Ville: 20 septembre 2026, 8 h a 16 h 30, a l''ecocentre.' where item_id = 14 and language_code = 'fr';
insert into sorting_item_example (item_id, language_code, position, example) values (14, 'fr', 0, 'releves bancaires');
insert into sorting_item_example (item_id, language_code, position, example) values (14, 'fr', 1, 'documents fiscaux');
insert into sorting_item_example (item_id, language_code, position, example) values (14, 'fr', 2, 'documents personnels');
update sorting_item_translation set availability = 'Free service several times per year. City-listed next date: September 20, 2026, 8:00 AM to 4:30 PM, at the ecocentre.' where item_id = 14 and language_code = 'en';
insert into sorting_item_example (item_id, language_code, position, example) values (14, 'en', 0, 'bank statements');
insert into sorting_item_example (item_id, language_code, position, example) values (14, 'en', 1, 'tax documents');
insert into sorting_item_example (item_id, language_code, position, example) values (14, 'en', 2, 'personal papers');
update sorting_item_translation set availability = '每年多次免费服务。市政府当前列出的下一次日期：2026 年 9 月 20 日，8:00-16:30，地点在 Écocentre。' where item_id = 14 and language_code = 'zh';
insert into sorting_item_example (item_id, language_code, position, example) values (14, 'zh', 0, '银行账单');
insert into sorting_item_example (item_id, language_code, position, example) values (14, 'zh', 1, '税务文件');
insert into sorting_item_example (item_id, language_code, position, example) values (14, 'zh', 2, '个人文件');
update sorting_item_translation set availability = 'Service gratuit avec Arbressence. Le ramassage est fait dans les 48 heures ouvrables apres communication.' where item_id = 15 and language_code = 'fr';
insert into sorting_item_example (item_id, language_code, position, example) values (15, 'fr', 0, 'feuillage de cedre');
insert into sorting_item_example (item_id, language_code, position, example) values (15, 'fr', 1, 'retailles de haie de cedre');
update sorting_item_translation set availability = 'Free service with Arbressence. Pickup is made within 48 business hours after contacting them.' where item_id = 15 and language_code = 'en';
insert into sorting_item_example (item_id, language_code, position, example) values (15, 'en', 0, 'cedar foliage');
insert into sorting_item_example (item_id, language_code, position, example) values (15, 'en', 1, 'cedar hedge trimmings');
update sorting_item_translation set availability = 'Arbressence 提供免费收集。联系后通常在 48 个工作小时内收取。' where item_id = 15 and language_code = 'zh';
insert into sorting_item_example (item_id, language_code, position, example) values (15, 'zh', 0, '雪松叶');
insert into sorting_item_example (item_id, language_code, position, example) values (15, 'zh', 1, '雪松篱笆修剪物');
