-- The sorting guide, from the city's own list rather than a sample of it.
--
-- Source: Ville de Blainville, "Calendrier des collectes residentielles 2026",
-- page 2 - the bac brun / bac bleu / bac noir / encombrants panels. V3 seeded
-- broad categories ("Contenants et emballages"); this adds the specific
-- objects the document actually names, which are the words a resident types.
--
-- Chosen for where the answer is surprising, because that is where a sorting
-- guide earns its keep. Compostable utensils go in the BLACK bin, not the
-- brown one, and the document says why; the same paper towel is organic or
-- garbage depending on whether it met food or a cleaning product; broken
-- mirror is a bulky pickup rather than a bin.
--
-- Generated by a script rather than typed, like V11: 22 items across three
-- languages over four tables is exactly the transcription where a silent
-- mistake hides. The ids come from last_insert_id() rather than being
-- assumed, so this does not depend on where auto_increment happens to be.

insert into sorting_item (destination_type, bin_color, source_url) values ('organic', 'brown', 'https://blainville.ca/services/environnement-et-voirie/matieres-organiques');
set @id = last_insert_id();
insert into sorting_item_translation (item_id, language_code, name, instruction) values (@id, 'fr', 'Viandes et os', 'Les viandes crues ou cuites vont au bac brun, avec les os et le gras.'), (@id, 'en', 'Meat and bones', 'Raw or cooked meat goes in the brown bin, bones and fat included.'), (@id, 'zh', '肉类和骨头', '生熟肉类连同骨头和油脂一起放入棕桶。');
insert into sorting_item_example (item_id, language_code, position, example) values (@id, 'fr', 0, 'viande crue'), (@id, 'fr', 1, 'viande cuite'), (@id, 'fr', 2, 'os de poulet'), (@id, 'fr', 3, 'gras'), (@id, 'en', 0, 'raw meat'), (@id, 'en', 1, 'cooked meat'), (@id, 'en', 2, 'chicken bones'), (@id, 'en', 3, 'fat'), (@id, 'zh', 0, '生肉'), (@id, 'zh', 1, '熟肉'), (@id, 'zh', 2, '骨头'), (@id, 'zh', 3, '油脂');
insert into sorting_item_keyword (item_id, language_code, keyword) values (@id, 'fr', 'viande'), (@id, 'fr', 'poulet'), (@id, 'fr', 'volaille'), (@id, 'fr', 'gras'), (@id, 'fr', 'ossements'), (@id, 'en', 'meat'), (@id, 'en', 'chicken'), (@id, 'en', 'poultry'), (@id, 'en', 'bones'), (@id, 'en', 'fat'), (@id, 'zh', '肉'), (@id, 'zh', '鸡肉'), (@id, 'zh', '骨头'), (@id, 'zh', '油脂');

insert into sorting_item (destination_type, bin_color, source_url) values ('organic', 'brown', 'https://blainville.ca/services/environnement-et-voirie/matieres-organiques');
set @id = last_insert_id();
insert into sorting_item_translation (item_id, language_code, name, instruction) values (@id, 'fr', 'Poissons et fruits de mer', 'Les poissons, leurs aretes et les fruits de mer vont au bac brun.'), (@id, 'en', 'Fish and seafood', 'Fish, fish bones and seafood go in the brown bin.'), (@id, 'zh', '鱼类和海鲜', '鱼、鱼骨和海鲜放入棕桶。');
insert into sorting_item_example (item_id, language_code, position, example) values (@id, 'fr', 0, 'poisson'), (@id, 'fr', 1, 'aretes'), (@id, 'fr', 2, 'crevettes'), (@id, 'fr', 3, 'coquillages'), (@id, 'en', 0, 'fish'), (@id, 'en', 1, 'fish bones'), (@id, 'en', 2, 'shrimp'), (@id, 'en', 3, 'shellfish'), (@id, 'zh', 0, '鱼'), (@id, 'zh', 1, '鱼骨'), (@id, 'zh', 2, '虾'), (@id, 'zh', 3, '贝类');
insert into sorting_item_keyword (item_id, language_code, keyword) values (@id, 'fr', 'poisson'), (@id, 'fr', 'aretes'), (@id, 'fr', 'fruits de mer'), (@id, 'en', 'fish'), (@id, 'en', 'seafood'), (@id, 'en', 'bones'), (@id, 'zh', '鱼'), (@id, 'zh', '鱼骨'), (@id, 'zh', '海鲜');

insert into sorting_item (destination_type, bin_color, source_url) values ('organic', 'brown', 'https://blainville.ca/services/environnement-et-voirie/matieres-organiques');
set @id = last_insert_id();
insert into sorting_item_translation (item_id, language_code, name, instruction) values (@id, 'fr', 'Oeufs et coquilles', 'Les oeufs et leurs coquilles vont au bac brun.'), (@id, 'en', 'Eggs and eggshells', 'Eggs and their shells go in the brown bin.'), (@id, 'zh', '鸡蛋和蛋壳', '鸡蛋和蛋壳放入棕桶。');
insert into sorting_item_example (item_id, language_code, position, example) values (@id, 'fr', 0, 'oeufs'), (@id, 'fr', 1, 'coquilles d''oeufs'), (@id, 'en', 0, 'eggs'), (@id, 'en', 1, 'eggshells'), (@id, 'zh', 0, '鸡蛋'), (@id, 'zh', 1, '蛋壳');
insert into sorting_item_keyword (item_id, language_code, keyword) values (@id, 'fr', 'oeuf'), (@id, 'fr', 'coquille'), (@id, 'en', 'egg'), (@id, 'en', 'eggshell'), (@id, 'zh', '鸡蛋'), (@id, 'zh', '蛋壳');

insert into sorting_item (destination_type, bin_color, source_url) values ('organic', 'brown', 'https://blainville.ca/services/environnement-et-voirie/matieres-organiques');
set @id = last_insert_id();
insert into sorting_item_translation (item_id, language_code, name, instruction) values (@id, 'fr', 'Produits laitiers solides', 'Le fromage, le beurre et le yogourt vont au bac brun.'), (@id, 'en', 'Solid dairy products', 'Cheese, butter and yogurt go in the brown bin.'), (@id, 'zh', '固体乳制品', '奶酪、黄油和酸奶放入棕桶。');
insert into sorting_item_example (item_id, language_code, position, example) values (@id, 'fr', 0, 'fromage'), (@id, 'fr', 1, 'beurre'), (@id, 'fr', 2, 'yogourt'), (@id, 'en', 0, 'cheese'), (@id, 'en', 1, 'butter'), (@id, 'en', 2, 'yogurt'), (@id, 'zh', 0, '奶酪'), (@id, 'zh', 1, '黄油'), (@id, 'zh', 2, '酸奶');
insert into sorting_item_keyword (item_id, language_code, keyword) values (@id, 'fr', 'fromage'), (@id, 'fr', 'beurre'), (@id, 'fr', 'yogourt'), (@id, 'fr', 'laitier'), (@id, 'en', 'cheese'), (@id, 'en', 'butter'), (@id, 'en', 'yogurt'), (@id, 'en', 'dairy'), (@id, 'zh', '奶酪'), (@id, 'zh', '黄油'), (@id, 'zh', '酸奶');

insert into sorting_item (destination_type, bin_color, source_url) values ('organic', 'brown', 'https://blainville.ca/services/environnement-et-voirie/matieres-organiques');
set @id = last_insert_id();
insert into sorting_item_translation (item_id, language_code, name, instruction) values (@id, 'fr', 'Residus de the et de cafe', 'Les residus de the, de tisane et de cafe vont au bac brun.'), (@id, 'en', 'Tea and coffee grounds', 'Tea, herbal tea and coffee residue go in the brown bin.'), (@id, 'zh', '茶渣和咖啡渣', '茶叶、花草茶和咖啡渣放入棕桶。');
insert into sorting_item_example (item_id, language_code, position, example) values (@id, 'fr', 0, 'marc de cafe'), (@id, 'fr', 1, 'sachets de the'), (@id, 'fr', 2, 'tisane'), (@id, 'en', 0, 'coffee grounds'), (@id, 'en', 1, 'tea bags'), (@id, 'en', 2, 'herbal tea'), (@id, 'zh', 0, '咖啡渣'), (@id, 'zh', 1, '茶包'), (@id, 'zh', 2, '花草茶');
insert into sorting_item_keyword (item_id, language_code, keyword) values (@id, 'fr', 'cafe'), (@id, 'fr', 'the'), (@id, 'fr', 'tisane'), (@id, 'fr', 'marc'), (@id, 'en', 'coffee'), (@id, 'en', 'tea'), (@id, 'en', 'grounds'), (@id, 'zh', '咖啡'), (@id, 'zh', '茶'), (@id, 'zh', '茶渣');

insert into sorting_item (destination_type, bin_color, source_url) values ('organic', 'brown', 'https://blainville.ca/services/environnement-et-voirie/matieres-organiques');
set @id = last_insert_id();
insert into sorting_item_translation (item_id, language_code, name, instruction) values (@id, 'fr', 'Mouchoirs et serviettes de table', 'Les mouchoirs, serviettes de table et nappes en papier vont au bac brun.'), (@id, 'en', 'Tissues and paper napkins', 'Tissues, paper napkins and paper tablecloths go in the brown bin.'), (@id, 'zh', '纸巾和餐巾纸', '纸巾、餐巾纸和纸桌布放入棕桶。');
insert into sorting_item_example (item_id, language_code, position, example) values (@id, 'fr', 0, 'mouchoirs'), (@id, 'fr', 1, 'serviettes de table'), (@id, 'fr', 2, 'nappes en papier'), (@id, 'en', 0, 'tissues'), (@id, 'en', 1, 'paper napkins'), (@id, 'en', 2, 'paper tablecloths'), (@id, 'zh', 0, '纸巾'), (@id, 'zh', 1, '餐巾纸'), (@id, 'zh', 2, '纸桌布');
insert into sorting_item_keyword (item_id, language_code, keyword) values (@id, 'fr', 'mouchoir'), (@id, 'fr', 'serviette'), (@id, 'fr', 'nappe'), (@id, 'en', 'tissue'), (@id, 'en', 'napkin'), (@id, 'en', 'tablecloth'), (@id, 'zh', '纸巾'), (@id, 'zh', '餐巾'), (@id, 'zh', '桌布');

insert into sorting_item (destination_type, bin_color, source_url) values ('organic', 'brown', 'https://blainville.ca/services/environnement-et-voirie/matieres-organiques');
set @id = last_insert_id();
insert into sorting_item_translation (item_id, language_code, name, instruction) values (@id, 'fr', 'Cure-dents et batonnets en bois', 'Les cure-dents et les batonnets en bois vont au bac brun.'), (@id, 'en', 'Toothpicks and wooden sticks', 'Toothpicks and wooden sticks go in the brown bin.'), (@id, 'zh', '牙签和木棒', '牙签和木制小棒放入棕桶。');
insert into sorting_item_example (item_id, language_code, position, example) values (@id, 'fr', 0, 'cure-dents'), (@id, 'fr', 1, 'batonnets en bois'), (@id, 'fr', 2, 'brochettes'), (@id, 'en', 0, 'toothpicks'), (@id, 'en', 1, 'wooden sticks'), (@id, 'en', 2, 'skewers'), (@id, 'zh', 0, '牙签'), (@id, 'zh', 1, '木棒'), (@id, 'zh', 2, '竹签');
insert into sorting_item_keyword (item_id, language_code, keyword) values (@id, 'fr', 'cure-dent'), (@id, 'fr', 'batonnet'), (@id, 'fr', 'bois'), (@id, 'en', 'toothpick'), (@id, 'en', 'wooden stick'), (@id, 'zh', '牙签'), (@id, 'zh', '木棒');

insert into sorting_item (destination_type, bin_color, source_url) values ('recycling', 'blue', 'https://blainville.ca/services/environnement-et-voirie/matieres-recuperables');
set @id = last_insert_id();
insert into sorting_item_translation (item_id, language_code, name, instruction) values (@id, 'fr', 'Bouteille de vin', 'Les bouteilles de vin vont au bac bleu, avec leur bouchon ou leur couvercle.'), (@id, 'en', 'Wine bottle', 'Wine bottles go in the blue bin, with their cap or lid.'), (@id, 'zh', '酒瓶', '酒瓶连同瓶盖放入蓝桶。');
insert into sorting_item_example (item_id, language_code, position, example) values (@id, 'fr', 0, 'bouteille de vin'), (@id, 'fr', 1, 'bouteille en verre'), (@id, 'en', 0, 'wine bottle'), (@id, 'en', 1, 'glass bottle'), (@id, 'zh', 0, '酒瓶'), (@id, 'zh', 1, '玻璃瓶');
insert into sorting_item_keyword (item_id, language_code, keyword) values (@id, 'fr', 'vin'), (@id, 'fr', 'bouteille'), (@id, 'fr', 'verre'), (@id, 'en', 'wine'), (@id, 'en', 'bottle'), (@id, 'en', 'glass'), (@id, 'zh', '酒瓶'), (@id, 'zh', '玻璃瓶');

insert into sorting_item (destination_type, bin_color, source_url) values ('recycling', 'blue', 'https://blainville.ca/services/environnement-et-voirie/matieres-recuperables');
set @id = last_insert_id();
insert into sorting_item_translation (item_id, language_code, name, instruction) values (@id, 'fr', 'Bouteille d''huile', 'Les bouteilles d''huile, en verre ou en plastique, vont au bac bleu.'), (@id, 'en', 'Oil bottle', 'Oil bottles, glass or plastic, go in the blue bin.'), (@id, 'zh', '食用油瓶', '食用油瓶，玻璃或塑料，均放入蓝桶。');
insert into sorting_item_example (item_id, language_code, position, example) values (@id, 'fr', 0, 'bouteille d''huile'), (@id, 'fr', 1, 'huile d''olive'), (@id, 'en', 0, 'oil bottle'), (@id, 'en', 1, 'olive oil'), (@id, 'zh', 0, '油瓶'), (@id, 'zh', 1, '橄榄油瓶');
insert into sorting_item_keyword (item_id, language_code, keyword) values (@id, 'fr', 'huile'), (@id, 'fr', 'bouteille'), (@id, 'en', 'oil'), (@id, 'en', 'bottle'), (@id, 'zh', '油瓶');

insert into sorting_item (destination_type, bin_color, source_url) values ('recycling', 'blue', 'https://blainville.ca/services/environnement-et-voirie/matieres-recuperables');
set @id = last_insert_id();
insert into sorting_item_translation (item_id, language_code, name, instruction) values (@id, 'fr', 'Boite de conserve', 'Les conserves vont au bac bleu. Les vider et les rincer legerement.'), (@id, 'en', 'Food can', 'Food cans go in the blue bin. Empty and lightly rinse them.'), (@id, 'zh', '罐头盒', '罐头盒放入蓝桶，倒空并简单冲洗。');
insert into sorting_item_example (item_id, language_code, position, example) values (@id, 'fr', 0, 'conserve'), (@id, 'fr', 1, 'boite de thon'), (@id, 'fr', 2, 'boite de soupe'), (@id, 'en', 0, 'can'), (@id, 'en', 1, 'tuna can'), (@id, 'en', 2, 'soup can'), (@id, 'zh', 0, '罐头'), (@id, 'zh', 1, '金枪鱼罐头'), (@id, 'zh', 2, '汤罐');
insert into sorting_item_keyword (item_id, language_code, keyword) values (@id, 'fr', 'conserve'), (@id, 'fr', 'boite'), (@id, 'fr', 'metal'), (@id, 'en', 'can'), (@id, 'en', 'tin'), (@id, 'en', 'metal'), (@id, 'zh', '罐头'), (@id, 'zh', '铁罐');

insert into sorting_item (destination_type, bin_color, source_url) values ('recycling', 'blue', 'https://blainville.ca/services/environnement-et-voirie/matieres-recuperables');
set @id = last_insert_id();
insert into sorting_item_translation (item_id, language_code, name, instruction) values (@id, 'fr', 'Boite a oeufs et casseau de fruits', 'Les boites a oeufs et les casseaux de fruits vont au bac bleu : ce sont des emballages.'), (@id, 'en', 'Egg carton and fruit basket', 'Egg cartons and fruit baskets go in the blue bin: they are packaging.'), (@id, 'zh', '蛋盒和水果盒', '蛋盒和水果盒属于包装，放入蓝桶。');
insert into sorting_item_example (item_id, language_code, position, example) values (@id, 'fr', 0, 'boite a oeufs'), (@id, 'fr', 1, 'casseau de fraises'), (@id, 'en', 0, 'egg carton'), (@id, 'en', 1, 'strawberry basket'), (@id, 'zh', 0, '蛋盒'), (@id, 'zh', 1, '草莓盒');
insert into sorting_item_keyword (item_id, language_code, keyword) values (@id, 'fr', 'boite a oeufs'), (@id, 'fr', 'casseau'), (@id, 'fr', 'emballage'), (@id, 'en', 'egg carton'), (@id, 'en', 'fruit basket'), (@id, 'en', 'packaging'), (@id, 'zh', '蛋盒'), (@id, 'zh', '水果盒');

insert into sorting_item (destination_type, bin_color, source_url) values ('recycling', 'blue', 'https://blainville.ca/services/environnement-et-voirie/matieres-recuperables');
set @id = last_insert_id();
insert into sorting_item_translation (item_id, language_code, name, instruction) values (@id, 'fr', 'Sac de croustilles', 'Les sacs de croustilles vont au bac bleu : ils servent a transporter un produit, donc ce sont des emballages.'), (@id, 'en', 'Chip bag', 'Chip bags go in the blue bin: they carry a product, so they count as packaging.'), (@id, 'zh', '薯片袋', '薯片袋用于盛装产品，属于包装，放入蓝桶。');
insert into sorting_item_example (item_id, language_code, position, example) values (@id, 'fr', 0, 'sac de croustilles'), (@id, 'fr', 1, 'sac de chips'), (@id, 'en', 0, 'chip bag'), (@id, 'en', 1, 'snack bag'), (@id, 'zh', 0, '薯片袋'), (@id, 'zh', 1, '零食袋');
insert into sorting_item_keyword (item_id, language_code, keyword) values (@id, 'fr', 'croustilles'), (@id, 'fr', 'chips'), (@id, 'fr', 'sac'), (@id, 'en', 'chips'), (@id, 'en', 'snack bag'), (@id, 'zh', '薯片袋'), (@id, 'zh', '零食袋');

insert into sorting_item (destination_type, bin_color, source_url) values ('recycling', 'blue', 'https://blainville.ca/services/environnement-et-voirie/matieres-recuperables');
set @id = last_insert_id();
insert into sorting_item_translation (item_id, language_code, name, instruction) values (@id, 'fr', 'Sac de papier', 'Les sacs de papier vont au bac bleu.'), (@id, 'en', 'Paper bag', 'Paper bags go in the blue bin.'), (@id, 'zh', '纸袋', '纸袋放入蓝桶。');
insert into sorting_item_example (item_id, language_code, position, example) values (@id, 'fr', 0, 'sac de papier'), (@id, 'fr', 1, 'sac brun'), (@id, 'en', 0, 'paper bag'), (@id, 'en', 1, 'brown bag'), (@id, 'zh', 0, '纸袋'), (@id, 'zh', 1, '牛皮纸袋');
insert into sorting_item_keyword (item_id, language_code, keyword) values (@id, 'fr', 'sac papier'), (@id, 'en', 'paper bag'), (@id, 'zh', '纸袋');

insert into sorting_item (destination_type, bin_color, source_url) values ('garbage', 'black', 'https://blainville.ca/services/environnement-et-voirie/ordures-menageres');
set @id = last_insert_id();
insert into sorting_item_translation (item_id, language_code, name, instruction) values (@id, 'fr', 'Vaisselle et sacs compostables ou biodegradables', 'Au bac noir, malgre leur nom. Ils se decomposent en petits fragments qui contaminent le plastique recyclable, et ils ne se degradent pas assez vite pour le bac brun.'), (@id, 'en', 'Compostable or biodegradable dishes and bags', 'In the black bin, despite the name. They break into small fragments that contaminate recyclable plastic, and they do not break down fast enough for the brown bin.'), (@id, 'zh', '可堆肥或可降解餐具和塑料袋', '尽管名字如此，仍放入黑桶。它们会碎成小颗粒污染可回收塑料，而分解速度又达不到棕桶的要求。');
insert into sorting_item_example (item_id, language_code, position, example) values (@id, 'fr', 0, 'ustensiles compostables'), (@id, 'fr', 1, 'sacs biodegradables'), (@id, 'fr', 2, 'contenants compostables'), (@id, 'en', 0, 'compostable utensils'), (@id, 'en', 1, 'biodegradable bags'), (@id, 'en', 2, 'compostable containers'), (@id, 'zh', 0, '可堆肥餐具'), (@id, 'zh', 1, '可降解塑料袋'), (@id, 'zh', 2, '可堆肥容器');
insert into sorting_item_keyword (item_id, language_code, keyword) values (@id, 'fr', 'compostable'), (@id, 'fr', 'biodegradable'), (@id, 'fr', 'ustensile'), (@id, 'en', 'compostable'), (@id, 'en', 'biodegradable'), (@id, 'en', 'utensil'), (@id, 'zh', '可堆肥'), (@id, 'zh', '可降解'), (@id, 'zh', '餐具');

insert into sorting_item (destination_type, bin_color, source_url) values ('garbage', 'black', 'https://blainville.ca/services/environnement-et-voirie/ordures-menageres');
set @id = last_insert_id();
insert into sorting_item_translation (item_id, language_code, name, instruction) values (@id, 'fr', 'Essuie-tout souille de produits chimiques', 'Au bac noir. Le meme essuie-tout va au bac brun s''il n''a servi qu''a de la nourriture.'), (@id, 'en', 'Paper towel with chemicals on it', 'In the black bin. The same paper towel goes in the brown bin if it only touched food.'), (@id, 'zh', '沾过化学品的厨房纸', '放入黑桶。同样的厨房纸，如果只沾过食物，则应放入棕桶。');
insert into sorting_item_example (item_id, language_code, position, example) values (@id, 'fr', 0, 'essuie-tout avec nettoyant'), (@id, 'fr', 1, 'chiffon avec produit'), (@id, 'en', 0, 'paper towel with cleaner'), (@id, 'en', 1, 'wipe with chemicals'), (@id, 'zh', 0, '沾清洁剂的厨房纸'), (@id, 'zh', 1, '沾化学品的抹布');
insert into sorting_item_keyword (item_id, language_code, keyword) values (@id, 'fr', 'essuie-tout'), (@id, 'fr', 'produit chimique'), (@id, 'fr', 'nettoyant'), (@id, 'en', 'paper towel'), (@id, 'en', 'chemical'), (@id, 'en', 'cleaner'), (@id, 'zh', '厨房纸'), (@id, 'zh', '化学品'), (@id, 'zh', '清洁剂');

insert into sorting_item (destination_type, bin_color, source_url) values ('garbage', 'black', 'https://blainville.ca/services/environnement-et-voirie/ordures-menageres');
set @id = last_insert_id();
insert into sorting_item_translation (item_id, language_code, name, instruction) values (@id, 'fr', 'Ampoule electrique', 'Les ampoules autres que fluocompactes vont au bac noir. Les fluocompactes se rapportent a l''ecocentre.'), (@id, 'en', 'Light bulb', 'Bulbs other than compact fluorescent go in the black bin. Compact fluorescent bulbs go to the ecocentre.'), (@id, 'zh', '灯泡', '除节能灯（紧凑型荧光灯）外的灯泡放入黑桶；节能灯需送到生态中心。');
insert into sorting_item_example (item_id, language_code, position, example) values (@id, 'fr', 0, 'ampoule incandescente'), (@id, 'fr', 1, 'ampoule DEL'), (@id, 'en', 0, 'incandescent bulb'), (@id, 'en', 1, 'LED bulb'), (@id, 'zh', 0, '白炽灯泡'), (@id, 'zh', 1, 'LED 灯泡');
insert into sorting_item_keyword (item_id, language_code, keyword) values (@id, 'fr', 'ampoule'), (@id, 'fr', 'lumiere'), (@id, 'en', 'bulb'), (@id, 'en', 'light'), (@id, 'zh', '灯泡');

insert into sorting_item (destination_type, bin_color, source_url) values ('garbage', 'black', 'https://blainville.ca/services/environnement-et-voirie/ordures-menageres');
set @id = last_insert_id();
insert into sorting_item_translation (item_id, language_code, name, instruction) values (@id, 'fr', 'Vaisselle cassee', 'La vaisselle cassee va au bac noir. Les morceaux de vitre ou de miroir casses vont plutot a la collecte d''encombrants.'), (@id, 'en', 'Broken dishes', 'Broken dishes go in the black bin. Broken glass or mirror pieces go to the bulky collection instead.'), (@id, 'zh', '破碎餐具', '破碎餐具放入黑桶；碎玻璃和碎镜子则属于大件垃圾收集。');
insert into sorting_item_example (item_id, language_code, position, example) values (@id, 'fr', 0, 'assiette cassee'), (@id, 'fr', 1, 'tasse cassee'), (@id, 'en', 0, 'broken plate'), (@id, 'en', 1, 'broken cup'), (@id, 'zh', 0, '破盘子'), (@id, 'zh', 1, '破杯子');
insert into sorting_item_keyword (item_id, language_code, keyword) values (@id, 'fr', 'vaisselle cassee'), (@id, 'fr', 'assiette'), (@id, 'en', 'broken dish'), (@id, 'en', 'plate'), (@id, 'zh', '破碎餐具'), (@id, 'zh', '盘子');

insert into sorting_item (destination_type, bin_color, source_url) values ('garbage', 'black', 'https://blainville.ca/services/environnement-et-voirie/ordures-menageres');
set @id = last_insert_id();
insert into sorting_item_translation (item_id, language_code, name, instruction) values (@id, 'fr', 'Plastique sans symbole', 'Au bac noir si ce n''est ni un contenant ni un emballage. Le bac bleu accepte les contenants, les emballages et les imprimes, c''est tout.'), (@id, 'en', 'Plastic with no recycling symbol', 'In the black bin if it is neither a container nor packaging. The blue bin takes containers, packaging and printed paper, and nothing else.'), (@id, 'zh', '无回收标志的塑料', '若既不是容器也不是包装，放入黑桶。蓝桶只收容器、包装和印刷品，仅此三类。');
insert into sorting_item_example (item_id, language_code, position, example) values (@id, 'fr', 0, 'objet en plastique'), (@id, 'fr', 1, 'piece en plastique'), (@id, 'en', 0, 'plastic object'), (@id, 'en', 1, 'plastic part'), (@id, 'zh', 0, '塑料物件'), (@id, 'zh', 1, '塑料零件');
insert into sorting_item_keyword (item_id, language_code, keyword) values (@id, 'fr', 'plastique'), (@id, 'fr', 'symbole'), (@id, 'en', 'plastic'), (@id, 'en', 'symbol'), (@id, 'zh', '塑料'), (@id, 'zh', '标志');

insert into sorting_item (destination_type, bin_color, source_url) values ('bulky', 'none', 'https://blainville.ca/services/environnement-et-voirie/collectes-et-matieres-residuelles');
set @id = last_insert_id();
insert into sorting_item_translation (item_id, language_code, name, instruction) values (@id, 'fr', 'Morceaux de vitre ou de miroir casses', 'A la collecte d''encombrants, pas au bac noir. Les deposer de facon securitaire, dans une boite en carton ou un sac en papier.'), (@id, 'en', 'Broken glass or mirror', 'To the bulky collection, not the black bin. Put them out safely, in a cardboard box or a paper bag.'), (@id, 'zh', '碎玻璃和碎镜子', '属于大件垃圾收集，不要放入黑桶。请安全地装入纸箱或纸袋后放置。');
insert into sorting_item_example (item_id, language_code, position, example) values (@id, 'fr', 0, 'vitre cassee'), (@id, 'fr', 1, 'miroir casse'), (@id, 'en', 0, 'broken window glass'), (@id, 'en', 1, 'broken mirror'), (@id, 'zh', 0, '碎玻璃'), (@id, 'zh', 1, '碎镜子');
insert into sorting_item_keyword (item_id, language_code, keyword) values (@id, 'fr', 'vitre'), (@id, 'fr', 'miroir'), (@id, 'fr', 'verre casse'), (@id, 'en', 'glass'), (@id, 'en', 'mirror'), (@id, 'en', 'broken glass'), (@id, 'zh', '玻璃'), (@id, 'zh', '镜子'), (@id, 'zh', '碎玻璃');

insert into sorting_item (destination_type, bin_color, source_url) values ('bulky', 'none', 'https://blainville.ca/services/environnement-et-voirie/collectes-et-matieres-residuelles');
set @id = last_insert_id();
insert into sorting_item_translation (item_id, language_code, name, instruction) values (@id, 'fr', 'Chauffe-eau, lavabo et toilette', 'A la collecte d''encombrants, sur demande en ligne. Maximum 90 kg et 1,8 m sur 1,2 m par article.'), (@id, 'en', 'Water heater, sink and toilet', 'To the bulky collection, on request. Maximum 90 kg and 1.8 m by 1.2 m per item.'), (@id, 'zh', '热水器、洗手盆和马桶', '属于大件垃圾收集，需在线申请。单件最重 90 公斤，最大 1.8 米 × 1.2 米。');
insert into sorting_item_example (item_id, language_code, position, example) values (@id, 'fr', 0, 'chauffe-eau'), (@id, 'fr', 1, 'lavabo'), (@id, 'fr', 2, 'toilette'), (@id, 'en', 0, 'water heater'), (@id, 'en', 1, 'sink'), (@id, 'en', 2, 'toilet'), (@id, 'zh', 0, '热水器'), (@id, 'zh', 1, '洗手盆'), (@id, 'zh', 2, '马桶');
insert into sorting_item_keyword (item_id, language_code, keyword) values (@id, 'fr', 'chauffe-eau'), (@id, 'fr', 'lavabo'), (@id, 'fr', 'toilette'), (@id, 'en', 'water heater'), (@id, 'en', 'sink'), (@id, 'en', 'toilet'), (@id, 'zh', '热水器'), (@id, 'zh', '洗手盆'), (@id, 'zh', '马桶');

insert into sorting_item (destination_type, bin_color, source_url) values ('bulky', 'none', 'https://blainville.ca/services/environnement-et-voirie/collectes-et-matieres-residuelles');
set @id = last_insert_id();
insert into sorting_item_translation (item_id, language_code, name, instruction) values (@id, 'fr', 'Electromenager et BBQ', 'A la collecte d''encombrants : electromenagers sans halocarbure, BBQ sans bonbonne. Un appareil contenant un halocarbure se rapporte a l''ecocentre.'), (@id, 'en', 'Appliance and BBQ', 'To the bulky collection: appliances without halocarbon, BBQ without its tank. An appliance containing halocarbon goes to the ecocentre.'), (@id, 'zh', '家电和烧烤炉', '属于大件垃圾收集：不含卤代烃的家电、不带气罐的烧烤炉。含卤代烃的电器须送生态中心。');
insert into sorting_item_example (item_id, language_code, position, example) values (@id, 'fr', 0, 'cuisiniere'), (@id, 'fr', 1, 'laveuse'), (@id, 'fr', 2, 'BBQ sans bonbonne'), (@id, 'en', 0, 'stove'), (@id, 'en', 1, 'washing machine'), (@id, 'en', 2, 'BBQ without tank'), (@id, 'zh', 0, '炉灶'), (@id, 'zh', 1, '洗衣机'), (@id, 'zh', 2, '不带气罐的烧烤炉');
insert into sorting_item_keyword (item_id, language_code, keyword) values (@id, 'fr', 'electromenager'), (@id, 'fr', 'BBQ'), (@id, 'fr', 'halocarbure'), (@id, 'en', 'appliance'), (@id, 'en', 'BBQ'), (@id, 'en', 'halocarbon'), (@id, 'zh', '家电'), (@id, 'zh', '烧烤炉');

-- The one instruction on the whole calendar that changes what a resident does
-- tonight: "Les bacs [...] doivent etre mis en bordure de rue avant 6 h, les
-- jours de collecte." It belongs on every generated occurrence, so it is
-- appended to each rule's note rather than left in a PDF.
update collection_schedule_rule set
    note_fr = concat(note_fr, ' Bacs en bordure de rue avant 6 h.'),
    note_en = concat(note_en, ' Bins at the curb before 6 a.m.'),
    note_zh = concat(note_zh, ' 收集日请在早上 6 点前将垃圾桶放到路边。');

-- Those notes are copied onto occurrences at generation time, so the ones
-- already materialized still carry the old text. Clearing the forward window
-- lets the top-up rewrite them; nothing before today is touched.
delete from collection_event where auto_generated = true and collection_date >= current_date;
update collection_schedule_rule set generated_through = date_sub(current_date, interval 1 day)
where generated_through > date_sub(current_date, interval 1 day);
