package com.bienvenueblainville.push;

import io.jsonwebtoken.Claims;
import io.jsonwebtoken.Jwts;
import org.junit.jupiter.api.Test;

import java.security.KeyPair;
import java.time.Clock;
import java.time.Instant;
import java.time.ZoneOffset;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;

/**
 * The header a push service checks before it accepts anything.
 *
 * <p>ES256 is where a JWT signer usually goes wrong: the JDK signs ECDSA into
 * a DER structure, while JWS wants the raw r‖s pair, and a signature in the
 * wrong shape is a 401 from every push service with nothing in the log to say
 * why. The fixture below was produced by the {@code web-push} npm library, and
 * one of these tests verifies it with the same code path that signs - so the
 * two implementations are checked against each other rather than each against
 * itself.
 */
class VapidAuthenticationTest {
    // Generated by `webpush.generateVAPIDKeys()` and signed by
    // `webpush.getVapidHeaders(...)` for this audience and subject.
    private static final String REFERENCE_PUBLIC =
            "BJX1f4oKaluqD9KfY868_KZyA0nNqCFao5xWFDuudr-N5QKNf61tFaOoHIRLI3uKRDTeAoHVfmhBhpW1hNadOb4";
    private static final String REFERENCE_PRIVATE = "bfahS-4sCxZX09GPu1C-8oa586OYfKeI18tA3MbREPs";
    private static final String REFERENCE_TOKEN =
            "eyJ0eXAiOiJKV1QiLCJhbGciOiJFUzI1NiJ9.eyJhdWQiOiJodHRwczovL2ZjbS5nb29nbGVhcGlzLmNvbSIsImV"
            + "4cCI6MTc5MTA5OTY0Niwic3ViIjoibWFpbHRvOmluZm9AYmxhaW52aWxsZS5jYSJ9.v9yQ2BAOdM1fZLDBAimO"
            + "NuqDGiMXcNhRglgXLQ_F2jTKhyFoEdPXmboPpGTM6uFgxGIU06-tCAf0uZ-ob-MlGw";

    private static VapidAuthentication authentication(Clock clock) {
        return new VapidAuthentication(
                VapidKeys.of(REFERENCE_PUBLIC, REFERENCE_PRIVATE), "mailto:info@blainville.ca", clock);
    }

    @Test
    void acceptsATokenTheReferenceLibrarySigned() {
        KeyPair keys = VapidKeys.of(REFERENCE_PUBLIC, REFERENCE_PRIVATE).keyPair();

        Claims claims = Jwts.parser()
                .verifyWith(keys.getPublic())
                .clock(() -> java.util.Date.from(Instant.ofEpochSecond(1_791_000_000L)))
                .build()
                .parseSignedClaims(REFERENCE_TOKEN)
                .getPayload();

        assertThat(claims.getAudience()).containsExactly("https://fcm.googleapis.com");
        assertThat(claims.getSubject()).isEqualTo("mailto:info@blainville.ca");
    }

    @Test
    void signsATokenThatVerifiesAgainstTheSamePublicKey() {
        Clock clock = Clock.fixed(Instant.parse("2026-10-03T00:00:00Z"), ZoneOffset.UTC);

        String header = authentication(clock).headerFor("https://updates.push.services.mozilla.com/wpush/v2/abc123");

        assertThat(header).startsWith("vapid t=").contains(", k=" + REFERENCE_PUBLIC);
        String token = header.substring("vapid t=".length(), header.indexOf(", k="));

        Claims claims = Jwts.parser()
                .verifyWith(VapidKeys.of(REFERENCE_PUBLIC, REFERENCE_PRIVATE).keyPair().getPublic())
                .clock(() -> java.util.Date.from(Instant.parse("2026-10-03T01:00:00Z")))
                .build()
                .parseSignedClaims(token)
                .getPayload();

        assertThat(claims.getSubject()).isEqualTo("mailto:info@blainville.ca");
    }

    @Test
    void signsTheOriginRatherThanTheWholeEndpoint() {
        // The audience is the push service's origin. Signing the full endpoint
        // URL is rejected by every push service and looks fine in a log.
        Clock clock = Clock.fixed(Instant.parse("2026-10-03T00:00:00Z"), ZoneOffset.UTC);
        String header = authentication(clock)
                .headerFor("https://updates.push.services.mozilla.com/wpush/v2/abc123?x=1");
        String token = header.substring("vapid t=".length(), header.indexOf(", k="));

        Claims claims = Jwts.parser()
                .verifyWith(VapidKeys.of(REFERENCE_PUBLIC, REFERENCE_PRIVATE).keyPair().getPublic())
                .clock(() -> java.util.Date.from(Instant.parse("2026-10-03T01:00:00Z")))
                .build()
                .parseSignedClaims(token)
                .getPayload();

        assertThat(claims.getAudience()).containsExactly("https://updates.push.services.mozilla.com");
    }

    @Test
    void keepsAPortWhenThePushServiceHasOne() {
        assertThat(VapidAuthentication.origin("https://push.example:8443/wpush/v2/abc"))
                .isEqualTo("https://push.example:8443");
    }

    @Test
    void refusesAnEndpointThatIsNotAnAbsoluteUrl() {
        assertThatThrownBy(() -> VapidAuthentication.origin("/wpush/v2/abc"))
                .isInstanceOf(IllegalArgumentException.class);
    }

    @Test
    void expiresWellInsideTheTwentyFourHoursTheSpecAllows() {
        Clock clock = Clock.fixed(Instant.parse("2026-10-03T00:00:00Z"), ZoneOffset.UTC);
        String header = authentication(clock).headerFor("https://push.example/wpush/v2/abc");
        String token = header.substring("vapid t=".length(), header.indexOf(", k="));

        Claims claims = Jwts.parser()
                .verifyWith(VapidKeys.of(REFERENCE_PUBLIC, REFERENCE_PRIVATE).keyPair().getPublic())
                .clock(() -> java.util.Date.from(Instant.parse("2026-10-03T01:00:00Z")))
                .build()
                .parseSignedClaims(token)
                .getPayload();

        assertThat(claims.getExpiration().toInstant())
                .isBefore(Instant.parse("2026-10-04T00:00:00Z"))
                .isAfter(Instant.parse("2026-10-03T00:00:00Z"));
    }
}
